version: '3'

services:
  web:
    image: your_username/your_repository
    ports:
      - "8080:80"  # 将宿主机的8080端口映射到容器的80端口
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8181:80"  # 将宿主机的8181端口映射到phpMyAdmin容器的80端口
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: example
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
